- config/17.7/ports.conf
- config/18.1/ports.conf
This is required for:
https://github.com/opnsense/plugins/issues/452
This closes #63.
-=david=-
> Add in node_exporter as a port.

- README.md
Hi there,
I added a link to freebsd.org for the lazy.
Cheers,
tpltnt
> link to freebsd.org

- build/arm.sh
- config/19.1/SMP-RPI2
- device/rpi2.conf
@fichtner Hope you can review this pull, see if it works or not.
> Kernel and Device config for Raspberry Pi 2

- config/19.1/ports.conf
Successfully compiled on arm/arm64
http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1/latest/All/
> Enable Python2/3 ports

- config/19.7/plugins.conf
- config/19.7/ports.conf
required for https://github.com/opnsense/plugins/pull/1392
> add net/google-cloud-sdk

- config/20.7/ports.conf
Prepare move to zabbix5 with 20.7
> Add zabbix5-* to ports.conf

- config/20.7/make.conf
@fichtner Sorry, I initially forgot to add/adjust the build options :cry:
> config: add build options for haproxy20

- config/21.1/make.conf
- config/21.1/plugins.conf
- config/21.1/ports.conf
required for https://github.com/opnsense/plugins/pull/2293
> add new port/plugin: emulators/qemu-guest-agent

- config/21.1/plugins.conf
- config/21.1/ports.conf
https://github.com/opnsense/plugins/pull/2358
> Add puppet-agent plugin

- config/21.7/make.conf
- config/21.7/ports.conf
- config/22.1/make.conf
- config/22.1/ports.conf
for https://github.com/opnsense/plugins/issues/2644
It would be good to have a package in order to be able to start testing.
> add HAProxy 2.4 

- config/22.1/aux.conf
- config/22.1/plugins.conf
- config/22.1/ports.conf
https://github.com/opnsense/tools/issues/264#issuecomment-1033503509
> config/22.1: fix PRODUCT_ARCH aarch64 for ignore list

- config/22.1/ports.conf
- device/ROCKPRO64.conf
Adds a device config file for RockPro64.
> Add build support for RockPro64

- config/22.7/make.conf
Related to #328 .. I'd remove the one in my repo then, it seems this option is kind of use ...
https://github.com/mimugmail/opn-repo/issues/16
> Adjust make args for mosquitto port

- config/23.1/ports.conf
> Add Zabbix 6.4

- config/23.7/plugins.conf
- config/23.7/ports.conf
See packages on https://ftp.yrzr.tk/opnsense/FreeBSD:13:aarch64/23.7/MINT/23.7.r1/
> enable packages that can be built on aarch64

- build/common.sh
https://github.com/opnsense/tools/pull/367#issuecomment-1652237576
> Fix device-specific hooks not getting loaded

- config/24.1/make.conf
- config/24.7/make.conf
Required for: https://github.com/opnsense/plugins/pull/4112
Adds the Caddy Layer4 module to the build.
> www/caddy-custom: Add caddy-l4 module

- config/24.7/aux.conf
https://forum.opnsense.org/index.php?topic=35828.msg205942#msg205942
> Add Rust to 24.7 aux set on aarch64

- config/24.7/make.conf
Fixes: https://github.com/opnsense/tools/issues/428
> www/caddy-custom: Update dependencies of modules

- device/RPI.conf
Add compute module 3 and 4 (and io board) dtbs to the process
> Add support for compute module 3 and compute module 4

- config/25.1/ports.conf
https://docs.frrouting.org/en/latest/frr-reload.html
> add net/frr8-pythontools

- build/common.sh
fixes #467 
To my superficial understanding, I think this could be merged, but people with a better understanding of the build system should probably correct me if I'm wrong!
> blobless git clone

- config/25.1/ports.conf
Belongs to https://github.com/opnsense/plugins/issues/4662
> Add shadowsocks-rust

- config/25.1/ports.conf
For: https://github.com/opnsense/plugins/issues/4716
> net/frr: Add frr10-pythontools which also adds its dependency frr10
