opnsense/tools

config/18.1/make.conf
Without LUA support HAProxy will fail to start, rendering the HAProxy plugin unusable.
This is required to be able to switch to HAProxy 1.8 for OPNsense 18.1.
Refs https://github.com/opnsense/plugins/issues/224
=> enable LUA support for net/haproxy-devel

build/arm.sh
Need to test bananapi image first from https://drive.google.com/drive/folders/1bAWuECNJwu0LdJOpaIn-2MrTKZ8evGNY. If it boots, this should be safe to merge. Else need to rename the copied bananapi.dtb too.
=> build arm: fix bananapi.dtb file name

config/19.1/ports.conf
The FreeBSD port net/haproxy was recently switched to the 1.9 release series of HAProxy. As stated in https://github.com/opnsense/plugins/issues/1089 I'd rather stay on 1.8.x until 2.0 was released and stabilized.
HAProxy 1.8 moved to a new port:
https://www.freshports.org/net/haproxy18
=> keep HAProxy 1.8.x

config/19.7/plugins.conf
we can enable the build for LibreSSL since os-sensei does not specifically depend on OpenSSL/LibreSSL for now. The same holds true for elasticsearch5.
=> os-sunnyvalley: we can enable the build for LibreSSL

build/base.sh, build/kernel.sh
References to #181 , sorry for the duplicate.
As complained in [https://wiki.freebsd.org/A_Brief_Guide_To_Cross_Compiling_FreeBSD](https://wiki.freebsd.org/A_Brief_Guide_To_Cross_Compiling_FreeBSD), where $TARGET != $TARGET_ARCH, the object dir is "$MAKEOBJDIRPREFIX/$TARGET.$TARGET_ARCH"
So in this case -> /usr/obj/$TARGET.$TARGET_ARCH
=> Fixed object paths for cross compiling

Makefile, README.md
This allows one to place the OPNsense repositories in a different
location, e.g., /root/opnsense, rather than reusing the host's /usr.
=> Makefile: add $ROOTDIR support

build/kernel.sh
It's actually non-trivial to determine if you need to build the
kernel-toolchain or not -- host version not matching the target exactly
is a valid reason, among others.
Unconditionally build kernel-toolchain to err on the side of caution and
towards prevention of confusing build failures.  If the `base` target
has already been built then no building really happens here, we simply
walk through all of the bootstrap tools and determine they're all up to
date.
=> kernel: drop cross-build conditional for building kernel-toolchain

device/RPI.conf
RPI3 and RPI4 are combined together as in FreeBSD 13 builds.
=> enable RPI4 support for 22.1

device/ROCKPRO64.conf
Build would fail when writing to the image's MSDOSBOOT partition without 'sysctl kern.geom.debugflags=0x10'
=> Fix build failure during arm_install_uboot() on RockPro64

build/audit.sh, build/common.sh, build/distfiles.sh, build/options.sh, build/plugins.sh, build/ports.sh, build/test.sh
Currently, when assigning multiple items to a LIST, the following works:
```
make ports PORTSLIST="port/a
port/b"
```
while the following would fail:
```
make ports PORTSLIST="port/a port/b"
```
This patch makes comma, space and tab acceptable as delimiters instead of newline only.
=> build: Allow delimiters other than newline in {AUX,PLUGINS,PORTS}LIST

config/22.7/plugins.conf, config/22.7/ports.conf
Fixes build on aarch64 by disable node_exporter and nut. Building
these packages would fail due to freeipmi unavailability.
Fixes: #303
=> Fix aarch64 build

config/23.1/ports.conf
refs https://github.com/opnsense/plugins/issues/3283
@fichtner, the removed port `emulators/qemu-guest-agent` can probably be removed from the OPNsense ports tree when this was merged.
=> replace qemu-guest-agent with new qemu guestagent FLAVOR

config/23.7/ports.conf
Was added in 1aae3368facf313f8bd601a1fc28092aa7fc4444, but is broken on aarch64:
https://svnweb.freebsd.org/ports?view=revision&revision=536924
https://www.freshports.org/sysutils/freeipmi
=> config: ignore freeipmi on aarch64

config/24.1/make.conf
As explained here:
https://github.com/Monviech/os-caddy-plugin/issues/102
Change the build priority to `desec` and `porkbun` instead of `vultr`, since they have been especially requested in past issues of os-caddy-plugin.
The issue stems from `vultr` having different `libdns` dependencies than the other modules, making the build fail if it's included with certain other combinations of modules (e.g. `desec`).
=> Update make.conf for caddy-custom build to mitigate build errors

config/24.1/make.conf
Needed for: https://github.com/opnsense/plugins/pull/3851
The build checks out with xcaddy without any errors.
github.com/caddy-dns/google-domains has been removed because it's unmaintained.
=> www/caddy: caddy-custom build that includes all caddy-dns providers

config/24.1/make.conf
Requires: https://github.com/opnsense/ports/pull/190
Lock the whole build down with commit hashes and version tag. Upstream changes won't make the build fail all of a sudden now (or at least mitigates most of these issues.)
=> www/caddy-custom: Make current build reproducible

config/24.1/make.conf
Retention Policy: https://github.com/opnsense/plugins/issues/3872
Required for: https://github.com/opnsense/plugins/pull/3865
=> www/caddy: DNS Providers for os-caddy-1.5.3

config/24.1/make.conf
* Fix some build errors that are introduced due to a conflict between different libdns versions. caddy-dns mod.ts introduce dependencies to their libdns counterpart, e.g. caddy-dns/porkbun depends on libdns/porkbun.
* This dependency has been replaced using a "go mod replace" command that is passed via the xcaddy command. It replaces the libdns module with a custom patched one. The line can be completely removed in the future, since when the build error of the dependency has been fixed, it can be pulled from upstream again.
* The regession that is fixed is that cloudflare has newer dependencies than the rest of the dns modules. That forces indirect upgrades of libdns versions in modules and some smaller build errors in these modules are introduced (namely, uint and int errors at a few …
=> www/caddy-custom: Update dependencies of extra modules

config/24.1/make.conf
Upstream has been successfully patched:
https://github.com/libdns/desec/commit/a279f344b3a94dba7ef810dff5e3db31667957ad
https://github.com/caddy-dns/desec/commit/822a6a2014b221e8fa589fbcfd0395abe9ee90f6
=> www/caddy-custom: Update desec dependency, remove custom patch

config/24.1/make.conf
The caddy-custom port just /pretends/ to build 2.7.6 (package is still called that way.) But it actually builds 2.8.1 now, very sneaky.
References:
https://github.com/opnsense/tools/pull/400#issuecomment-2140805870
https://forum.opnsense.org/index.php?topic=35828.msg200025#msg200025
https://forum.opnsense.org/index.php?topic=35828.msg200033#msg200033
=> www/caddy-custom: Remove rfc2136 since it causes build with caddy-2.8.1 to fail

config/24.1/make.conf, config/24.7/make.conf
- Most of my upstream PRs got merged and new versions have been made. Removed all custom patches in favor of the upstream versions.
- copied this new stable config into 24.7 too
=> www/caddy-custom: Merge all upstream DNS Provider fixes into new build. Add 24.7 build.

config/24.1/make.conf, config/24.7/make.conf
References:
- https://www.reddit.com/r/opnsense/comments/1dwbr88/issue_using_oscaddy_to_generate_wildcard_cert/
- https://github.com/opnsense/plugins/pull/4073
=> www/caddy-custom: Update Route53 and Cloudflare dependencies.

config/24.7/make.conf
Build in xcaddy checks out, doesn't hurt adding this for the CLI crowd who only use this port without GUI in OPNsense.
Fixes: https://github.com/opnsense/plugins/issues/4236
=> www/caddy-custom: Add ratelimit module for CLI usage

config/24.7/make.conf
An important change is the update of caddy-l4 which might fix something. (yeah pretty vague but I got the hint to go to latest here.)
Might be this that has to be fixed for some users: https://github.com/mholt/caddy-l4/commit/22a03931ae46d0decc068e8d1ffe83e6187ed812
PR: https://forum.opnsense.org/index.php?topic=42955.0
At the same time I checked and some DNS Providers also had updates so put them in here too.
=> www/caddy-custom: Update dependencies

config/24.7/make.conf
Adds these two commits:
https://github.com/mholt/caddy-l4/commit/ea27408a3384a7f33b5d1cb49ec592cf76942be6
https://github.com/mholt/caddy-l4/commit/bdee6a6620c02aca4817e6c3091fed26aa10940c
Fixes (for now) that the TLS matcher in the Layer 4 module didn't work anymore due to some latest Chrome and Edge updates.
For tracking that issue:
https://github.com/mholt/caddy-l4/issues/250
PR: https://forum.opnsense.org/index.php?topic=42955.0
=> www/caddy-custom: Update layer4 module

config/24.7/plugins.conf
Zenarmor is not available for OPNsense aarch64.
Bug report: https://forum.opnsense.org/index.php?topic=35828.msg218005#msg218005
=> config/plugins: ignore Zenarmor vendor repository on aarch64

build/prefetch.sh
Building images now requires the `tests` set. Allow `make prefetch-tests` to speed up building images.
=> prefetch: add support for tests set

config/24.7/make.conf, config/25.1/make.conf
Update caddy-l4 module. Remove DNS Provider dependencies that pull big external deps/sdks into the binary.
For: https://github.com/opnsense/plugins/issues/4437
Fixes: https://github.com/opnsense/plugins/issues/4384
=> www/caddy-custom: Revise build for caddy-v2.9.0

build/vm.sh
Same procedure as in build/arm. Allows building aarch64 VM images on amd64 build systems.
=> build/vm: enable cross-building VM images

config/25.1/make.conf
https://github.com/opnsense/plugins/issues/4643
Reasons are explained in above ticket. To be merged when caddy-v2.10.0 hits the road. Merging it beforehand will make the current caddy build fail.
- Remove commit hashes requirement
Since our build is very lean now, compatibility issues between different modules are not a pressing issue anymore.
The exact versions of modules can be more lenient, as build issues will be very rare now.
The dependency which made builds fail has always been libdns, which is now on version 1.0.0, and hopefully will not introduce breaking changes anymore. Libdns is an integral dependency of caddy itself, and a dependency of dynamic-dns and cloudflare, as well as any other dns provider.
Removing the DNS providers from the standard build will remove the need for …
=> www/caddy-custom: Revise build for caddy-v2.10.0

config/25.1/ports.conf
Fails to build.
https://github.com/opnsense/plugins/issues/4662#issuecomment-2898196123
=> ports: exclude shadowsocks-rust on aarch64

config/25.1/ports.conf, config/25.7/ports.conf
Build error fixed by upstream patch: opnsense/ports@8df2f48
Context: opnsense/plugins#4662
=> ports: revert "exclude shadowsocks-rust on aarch64"
